var config = {
    texts: [
        "送给我",
        "心爱的女朋友",
        "今天是你的生日",
        "祝你生日快乐！！！",
        "希望你每一天都能像今天这样",
        "美丽而快乐",
        "我们的相遇",
        "实在是一种心动的奇迹",
        "今天是我们一起过的第一个生日",
        "希望今后的每一天",
        "都会有彼此的陪伴",
        "希望这只手",
        "还有这只手",
        "牵在一起",
        "一直走下去",
        "一起分享生活中的喜悦",
        "一起面对生活中的挑战",
        "一起诉说彼此的心声",
        "有你的陪伴",
        "三生有幸",
        "我爱你！",
        "————爱你的安先生"
    ],
    imgs: {
        "心爱的女朋友": "./imgs/you.jpg",
        "今天是你的生日": "./imgs/birthday.jpg",
        "祝你生日快乐！！！": "./imgs/bd1.jpg",
        "美丽而快乐": "./imgs/happy.jpg",
        "希望这只手": "./imgs/my_hand.jpg",
        "还有这只手": "./imgs/your_hand.jpg",
        "三生有幸": "./imgs/lucky.jpg",
        "我爱你！": "./imgs/i_love_you.jpg",
        "————爱你的安先生": "./imgs/me.jpg"
    },
    desc: {
        turn_on: "不知所措？点这里!",
        play: "来点音乐？",
        bannar_coming: "加点氛围？",
        balloons_flying: "好像少点东西？",
        cake_fadein: "蛋糕？",
        light_candle: "蜡烛？",
        wish_message: "亲爱的，生日快乐！",
        story: "A MESSAGE FOR YOU",
    }
};
